/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the plugin repository
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ObsidinectPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian9 = require("obsidian");

// src/constants.ts
var VIEW_TYPE_OBSIDINECT = "obsidinect-chat";
var MAX_TOOL_ROUNDS = 8;
var MAX_ATTACH_CHARS = 2e4;
var MAX_READ_CHARS = 8e4;
var MAX_SEARCH_HITS = 20;
var MAX_SEARCH_SCAN = 250;
var MAX_LIST_NOTES = 250;
var ANTHROPIC_VERSION = "2023-06-01";
var DEFAULT_MODELS = {
  anthropic: "claude-sonnet-4-5",
  openai: "gpt-4o",
  xai: "grok-3"
};
var DEFAULT_BASE_URLS = {
  anthropic: "https://api.anthropic.com",
  openai: "https://api.openai.com/v1",
  xai: "https://api.x.ai/v1"
};
var DEFAULT_SYSTEM_PROMPT = [
  "You are Obsidinect, an assistant inside the user's Obsidian vault on this device.",
  "Use tools to list, search, read, and edit markdown notes when that helps.",
  "Only change files the user asked you to change. Prefer short, concrete answers.",
  "When you write notes, use markdown. Never mention, repeat, or store API keys.",
  "Paths are relative to the vault root and must end in .md."
].join(" ");
var DEFAULT_SETTINGS = {
  provider: "anthropic",
  apiKey: "",
  model: DEFAULT_MODELS.anthropic,
  baseUrl: "",
  systemPrompt: DEFAULT_SYSTEM_PROMPT
};
var PROVIDER_LABELS = {
  anthropic: "Anthropic (Claude)",
  openai: "OpenAI (ChatGPT / compatible)",
  xai: "xAI (Grok)"
};

// src/providers/anthropic.ts
var import_obsidian = require("obsidian");

// src/safety.ts
var PathError = class extends Error {
  constructor(message) {
    super(message);
    this.name = "PathError";
  }
};
function sanitizeMarkdownPath(raw) {
  if (typeof raw !== "string" || !raw.trim()) {
    throw new PathError("A file path is required.");
  }
  let path = raw.trim().replace(/\\/g, "/");
  if (path.startsWith("/") || /^[a-zA-Z]:/.test(path)) {
    throw new PathError("Absolute paths are not allowed.");
  }
  const parts = path.split("/").filter((part) => part.length > 0);
  if (parts.length === 0) {
    throw new PathError("A file path is required.");
  }
  if (parts.some((part) => part === ".." || part === ".")) {
    throw new PathError("Path traversal is not allowed.");
  }
  path = parts.join("/");
  if (!path.includes(".")) {
    path += ".md";
  }
  if (!path.toLowerCase().endsWith(".md")) {
    throw new PathError("Only markdown (.md) files are allowed.");
  }
  return path;
}
function sanitizeFolderPath(raw) {
  if (raw == null || raw === "") {
    return void 0;
  }
  if (typeof raw !== "string") {
    throw new PathError("Folder must be a string.");
  }
  let path = raw.trim().replace(/\\/g, "/");
  if (!path) {
    return void 0;
  }
  if (path.startsWith("/") || /^[a-zA-Z]:/.test(path)) {
    throw new PathError("Absolute folder paths are not allowed.");
  }
  const parts = path.split("/").filter((part) => part.length > 0);
  if (parts.some((part) => part === ".." || part === ".")) {
    throw new PathError("Path traversal is not allowed.");
  }
  return parts.join("/");
}
function assertNoSecretInContent(content, apiKey) {
  if (apiKey && apiKey.length >= 8 && content.includes(apiKey)) {
    throw new Error("Refusing to write the API key into a note.");
  }
}
function joinUrl(base, suffix) {
  const cleanBase = base.replace(/\/+$/, "");
  const cleanSuffix = suffix.startsWith("/") ? suffix : `/${suffix}`;
  if (cleanBase.endsWith(cleanSuffix) || cleanBase.endsWith(cleanSuffix.replace(/^\//, ""))) {
    return cleanBase;
  }
  return `${cleanBase}${cleanSuffix}`;
}
function truncate(text, max) {
  if (text.length <= max) {
    return text;
  }
  return `${text.slice(0, max)}

[truncated ${text.length - max} characters]`;
}
function stripWrappingFences(text) {
  const trimmed = text.trim();
  const match = /^```(?:[a-zA-Z0-9_-]+)?\n([\s\S]*?)\n```$/.exec(trimmed);
  return match?.[1] ?? trimmed;
}
function pathMentionedInText(path, text) {
  const lower = text.toLowerCase();
  if (lower.includes(path.toLowerCase())) {
    return true;
  }
  const base = path.split("/").pop() ?? path;
  const stem = base.replace(/\.md$/i, "");
  return lower.includes(base.toLowerCase()) || lower.includes(stem.toLowerCase());
}

// src/providers/types.ts
var VAULT_TOOL_SPECS = [
  {
    name: "list_notes",
    description: "List markdown notes in the vault. Optionally limit to a folder.",
    parameters: {
      type: "object",
      properties: {
        folder: {
          type: "string",
          description: "Optional vault-relative folder, for example Projects or Daily."
        }
      }
    }
  },
  {
    name: "read_note",
    description: "Read the full markdown contents of a note.",
    parameters: {
      type: "object",
      properties: {
        path: { type: "string", description: "Vault-relative path ending in .md." }
      },
      required: ["path"]
    }
  },
  {
    name: "search_notes",
    description: "Search note titles, headings, and content for a query.",
    parameters: {
      type: "object",
      properties: {
        query: { type: "string", description: "Case-insensitive text to find." }
      },
      required: ["query"]
    }
  },
  {
    name: "write_note",
    description: "Create or overwrite a markdown note. Confirm with the user before overwriting unless they already asked to write this file.",
    parameters: {
      type: "object",
      properties: {
        path: { type: "string", description: "Vault-relative path ending in .md." },
        content: { type: "string", description: "Full markdown to write." }
      },
      required: ["path", "content"]
    }
  },
  {
    name: "append_note",
    description: "Append markdown to a note, creating it if it does not exist.",
    parameters: {
      type: "object",
      properties: {
        path: { type: "string", description: "Vault-relative path ending in .md." },
        content: { type: "string", description: "Markdown to append." }
      },
      required: ["path", "content"]
    }
  },
  {
    name: "replace_in_note",
    description: "Replace every occurrence of a string in a markdown note.",
    parameters: {
      type: "object",
      properties: {
        path: { type: "string", description: "Vault-relative path ending in .md." },
        old: { type: "string", description: "Exact text to find." },
        new: { type: "string", description: "Replacement text." }
      },
      required: ["path", "old", "new"]
    }
  }
];
function asString(value) {
  return typeof value === "string" ? value : "";
}
function asRecord(value) {
  if (value && typeof value === "object" && !Array.isArray(value)) {
    return value;
  }
  return {};
}
function safeApiError(status, body) {
  let message = body.trim().slice(0, 400);
  try {
    const parsed = JSON.parse(body);
    if (typeof parsed.error === "string") {
      message = parsed.error;
    } else if (parsed.error?.message) {
      message = parsed.error.message;
    } else if (parsed.message) {
      message = parsed.message;
    }
  } catch {
  }
  return `Provider returned HTTP ${status}: ${message}`;
}

// src/providers/anthropic.ts
function toAnthropicMessages(messages) {
  const out = [];
  for (const message of messages) {
    if (message.role === "user") {
      out.push({ role: "user", content: message.content });
      continue;
    }
    if (message.role === "assistant") {
      const content = [];
      if (message.content.trim()) {
        content.push({ type: "text", text: message.content });
      }
      for (const call of message.toolCalls ?? []) {
        content.push({
          type: "tool_use",
          id: call.id,
          name: call.name,
          input: call.input
        });
      }
      if (content.length === 0) {
        content.push({ type: "text", text: "" });
      }
      out.push({ role: "assistant", content });
      continue;
    }
    out.push({
      role: "user",
      content: message.results.map((result) => ({
        type: "tool_result",
        tool_use_id: result.id,
        content: result.content,
        is_error: result.isError ?? false
      }))
    });
  }
  return out;
}
var AnthropicProvider = class {
  async complete(request) {
    const base = request.settings.baseUrl.trim() || DEFAULT_BASE_URLS.anthropic;
    const url = joinUrl(base, "/v1/messages");
    const tools = request.disableTools ? void 0 : VAULT_TOOL_SPECS.map((spec) => ({
      name: spec.name,
      description: spec.description,
      input_schema: spec.parameters
    }));
    const response = await (0, import_obsidian.requestUrl)({
      url,
      method: "POST",
      contentType: "application/json",
      throw: false,
      headers: {
        "x-api-key": request.settings.apiKey,
        "anthropic-version": ANTHROPIC_VERSION
      },
      body: JSON.stringify({
        model: request.settings.model,
        max_tokens: 4096,
        system: request.systemPrompt,
        ...tools ? { tools } : {},
        messages: toAnthropicMessages(request.messages)
      })
    });
    if (response.status < 200 || response.status >= 300) {
      throw new Error(safeApiError(response.status, response.text));
    }
    const data = asRecord(response.json);
    const blocks = Array.isArray(data.content) ? data.content : [];
    const textParts = [];
    const toolCalls = [];
    for (const block of blocks) {
      if (block.type === "text" && block.text) {
        textParts.push(block.text);
      }
      if (block.type === "tool_use" && block.id && block.name) {
        toolCalls.push({
          id: block.id,
          name: block.name,
          input: asRecord(block.input)
        });
      }
    }
    return {
      text: textParts.join("\n").trim(),
      toolCalls
    };
  }
};

// src/providers/openai.ts
var import_obsidian2 = require("obsidian");
function openaiTools() {
  return VAULT_TOOL_SPECS.map((spec) => ({
    type: "function",
    function: {
      name: spec.name,
      description: spec.description,
      parameters: spec.parameters
    }
  }));
}
function toOpenAIMessages(systemPrompt, messages) {
  const out = [{ role: "system", content: systemPrompt }];
  for (const message of messages) {
    if (message.role === "user") {
      out.push({ role: "user", content: message.content });
      continue;
    }
    if (message.role === "assistant") {
      const toolCalls = (message.toolCalls ?? []).map((call) => ({
        id: call.id,
        type: "function",
        function: {
          name: call.name,
          arguments: JSON.stringify(call.input ?? {})
        }
      }));
      out.push({
        role: "assistant",
        content: message.content || null,
        ...toolCalls.length > 0 ? { tool_calls: toolCalls } : {}
      });
      continue;
    }
    for (const result of message.results) {
      out.push({
        role: "tool",
        tool_call_id: result.id,
        content: result.content
      });
    }
  }
  return out;
}
var OpenAICompatibleProvider = class {
  constructor(defaultBase) {
    this.defaultBase = defaultBase;
  }
  async complete(request) {
    const base = request.settings.baseUrl.trim() || this.defaultBase;
    const url = joinUrl(base, "/chat/completions");
    const response = await (0, import_obsidian2.requestUrl)({
      url,
      method: "POST",
      contentType: "application/json",
      throw: false,
      headers: {
        Authorization: `Bearer ${request.settings.apiKey}`
      },
      body: JSON.stringify({
        model: request.settings.model,
        max_tokens: 4096,
        ...request.disableTools ? {} : { tools: openaiTools() },
        messages: toOpenAIMessages(request.systemPrompt, request.messages)
      })
    });
    if (response.status < 200 || response.status >= 300) {
      throw new Error(safeApiError(response.status, response.text));
    }
    const data = asRecord(response.json);
    const choices = Array.isArray(data.choices) ? data.choices : [];
    const first = asRecord(choices[0]);
    const message = asRecord(first.message);
    const text = asString(message.content);
    const rawCalls = Array.isArray(message.tool_calls) ? message.tool_calls : [];
    const toolCalls = [];
    for (const raw of rawCalls) {
      const call = asRecord(raw);
      const fn = asRecord(call.function);
      let input = {};
      const args = asString(fn.arguments);
      if (args) {
        try {
          input = asRecord(JSON.parse(args));
        } catch {
          input = { raw: args };
        }
      }
      const id = asString(call.id) || `call_${toolCalls.length + 1}`;
      const name = asString(fn.name);
      if (name) {
        toolCalls.push({ id, name, input });
      }
    }
    return { text: text.trim(), toolCalls };
  }
};
var openAIProvider = new OpenAICompatibleProvider(DEFAULT_BASE_URLS.openai);

// src/providers/xai.ts
var xaiProvider = new OpenAICompatibleProvider(DEFAULT_BASE_URLS.xai);

// src/providers/index.ts
var anthropicProvider = new AnthropicProvider();
function getProvider(id) {
  if (id === "anthropic") {
    return anthropicProvider;
  }
  if (id === "xai") {
    return xaiProvider;
  }
  return openAIProvider;
}

// src/tools.ts
var import_obsidian4 = require("obsidian");

// src/confirm.ts
var import_obsidian3 = require("obsidian");
function confirmAction(app, title, message) {
  return new Promise((resolve) => {
    const modal = new ConfirmModal(app, title, message, (ok) => resolve(ok));
    modal.open();
  });
}
var ConfirmModal = class extends import_obsidian3.Modal {
  constructor(app, heading, message, onDecide) {
    super(app);
    this.heading = heading;
    this.message = message;
    this.onDecide = onDecide;
    this.decided = false;
  }
  onOpen() {
    this.titleEl.setText(this.heading);
    this.contentEl.createEl("p", { text: this.message, cls: "obsidinect-confirm-copy" });
    new import_obsidian3.Setting(this.contentEl).addButton(
      (btn) => btn.setButtonText("Cancel").onClick(() => {
        this.decide(false);
      })
    ).addButton(
      (btn) => btn.setButtonText("Overwrite").setWarning().onClick(() => {
        this.decide(true);
      })
    );
  }
  onClose() {
    if (!this.decided) {
      this.onDecide(false);
    }
  }
  decide(ok) {
    if (this.decided) {
      return;
    }
    this.decided = true;
    this.onDecide(ok);
    this.close();
  }
};

// src/tools.ts
async function runVaultTool(call, ctx) {
  try {
    const content = await dispatch(call.name, call.input, ctx);
    return { id: call.id, name: call.name, content };
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    return { id: call.id, name: call.name, content: message, isError: true };
  }
}
async function dispatch(name, input, ctx) {
  switch (name) {
    case "list_notes":
      return listNotes(ctx.app, input.folder);
    case "read_note":
      return readNote(ctx.app, input.path);
    case "search_notes":
      return searchNotes(ctx.app, input.query);
    case "write_note":
      return writeNote(ctx, String(input.path ?? ""), String(input.content ?? ""));
    case "append_note":
      return appendNote(ctx, String(input.path ?? ""), String(input.content ?? ""));
    case "replace_in_note":
      return replaceInNote(
        ctx,
        String(input.path ?? ""),
        String(input.old ?? ""),
        String(input.new ?? "")
      );
    default:
      throw new Error(`Unknown tool: ${name}`);
  }
}
function listNotes(app, folderRaw) {
  const folder = sanitizeFolderPath(folderRaw);
  const files = app.vault.getMarkdownFiles();
  const prefix = folder ? `${folder}/` : "";
  const matched = files.filter((file) => {
    if (!folder) {
      return true;
    }
    return file.path === `${folder}.md` ? false : file.path.startsWith(prefix);
  }).map((file) => file.path).sort((a, b) => a.localeCompare(b));
  if (folder && !app.vault.getAbstractFileByPath(folder) && matched.length === 0) {
    return `Folder not found: ${folder}`;
  }
  if (matched.length === 0) {
    return folder ? `No markdown notes in ${folder}.` : "No markdown notes in this vault.";
  }
  const shown = matched.slice(0, MAX_LIST_NOTES);
  const extra = matched.length - shown.length;
  return extra > 0 ? `${shown.join("\n")}

[${extra} more notes omitted]` : shown.join("\n");
}
async function readNote(app, pathRaw) {
  const path = sanitizeMarkdownPath(pathRaw);
  const file = app.vault.getAbstractFileByPath(path);
  if (!(file instanceof import_obsidian4.TFile)) {
    throw new Error(`Note not found: ${path}`);
  }
  const text = await app.vault.cachedRead(file);
  return truncate(text, MAX_READ_CHARS);
}
async function searchNotes(app, queryRaw) {
  if (typeof queryRaw !== "string" || !queryRaw.trim()) {
    throw new Error("query is required.");
  }
  const query = queryRaw.trim();
  const needle = query.toLowerCase();
  const files = app.vault.getMarkdownFiles();
  const hits = [];
  const seen = /* @__PURE__ */ new Set();
  const add = (line, path) => {
    if (seen.has(path) || hits.length >= MAX_SEARCH_HITS) {
      return;
    }
    seen.add(path);
    hits.push(line);
  };
  for (const file of files) {
    if (file.path.toLowerCase().includes(needle) || file.basename.toLowerCase().includes(needle)) {
      add(`${file.path} (filename)`, file.path);
    }
  }
  for (const file of files) {
    if (hits.length >= MAX_SEARCH_HITS) {
      break;
    }
    const cache = app.metadataCache.getFileCache(file);
    const headings = cache?.headings ?? [];
    if (headings.some((heading) => heading.heading.toLowerCase().includes(needle))) {
      add(`${file.path} (heading)`, file.path);
    }
  }
  let scanned = 0;
  for (const file of files) {
    if (hits.length >= MAX_SEARCH_HITS || scanned >= MAX_SEARCH_SCAN) {
      break;
    }
    if (seen.has(file.path)) {
      continue;
    }
    scanned += 1;
    const text = await app.vault.cachedRead(file);
    const idx = text.toLowerCase().indexOf(needle);
    if (idx >= 0) {
      const start = Math.max(0, idx - 80);
      const snippet = text.slice(start, idx + query.length + 80).replace(/\s+/g, " ").trim();
      add(`${file.path}: \u2026${snippet}\u2026`, file.path);
    }
  }
  if (hits.length === 0) {
    return `No matches for "${query}".`;
  }
  return hits.join("\n");
}
async function ensureParentFolders(app, path) {
  const parts = path.split("/").slice(0, -1);
  let acc = "";
  for (const part of parts) {
    acc = acc ? `${acc}/${part}` : part;
    const existing = app.vault.getAbstractFileByPath(acc);
    if (!existing) {
      await app.vault.createFolder(acc);
    } else if (!(existing instanceof import_obsidian4.TFolder)) {
      throw new Error(`Cannot create folder ${acc}: a file already exists there.`);
    }
  }
}
async function writeNote(ctx, pathRaw, content) {
  const path = sanitizeMarkdownPath(pathRaw);
  assertNoSecretInContent(content, ctx.apiKey);
  const existing = ctx.app.vault.getAbstractFileByPath(path);
  if (existing instanceof import_obsidian4.TFile) {
    const mentioned = pathMentionedInText(path, ctx.userTurnText);
    if (!mentioned) {
      const ok = await confirmAction(
        ctx.app,
        "Overwrite note?",
        `${path} already exists. Overwrite it with the model\u2019s draft?`
      );
      if (!ok) {
        throw new Error(`User declined to overwrite ${path}.`);
      }
    }
    await ctx.app.vault.modify(existing, content);
    new import_obsidian4.Notice(`Updated ${path}`);
    return `Updated ${path} (${content.length} characters).`;
  }
  if (existing) {
    throw new Error(`${path} exists but is not a markdown file.`);
  }
  await ensureParentFolders(ctx.app, path);
  await ctx.app.vault.create(path, content);
  new import_obsidian4.Notice(`Created ${path}`);
  return `Created ${path} (${content.length} characters).`;
}
async function appendNote(ctx, pathRaw, content) {
  const path = sanitizeMarkdownPath(pathRaw);
  assertNoSecretInContent(content, ctx.apiKey);
  const existing = ctx.app.vault.getAbstractFileByPath(path);
  if (existing instanceof import_obsidian4.TFile) {
    const current = await ctx.app.vault.read(existing);
    const next = current.endsWith("\n") || current.length === 0 ? `${current}${content}` : `${current}
${content}`;
    await ctx.app.vault.modify(existing, next);
    new import_obsidian4.Notice(`Appended ${path}`);
    return `Appended ${content.length} characters to ${path}.`;
  }
  if (existing) {
    throw new Error(`${path} exists but is not a markdown file.`);
  }
  await ensureParentFolders(ctx.app, path);
  await ctx.app.vault.create(path, content);
  new import_obsidian4.Notice(`Created ${path}`);
  return `Created ${path} with appended content.`;
}
async function replaceInNote(ctx, pathRaw, oldText, newText) {
  const path = sanitizeMarkdownPath(pathRaw);
  if (!oldText) {
    throw new Error("old is required.");
  }
  assertNoSecretInContent(newText, ctx.apiKey);
  const file = ctx.app.vault.getAbstractFileByPath(path);
  if (!(file instanceof import_obsidian4.TFile)) {
    throw new Error(`Note not found: ${path}`);
  }
  const current = await ctx.app.vault.read(file);
  if (!current.includes(oldText)) {
    throw new Error(`Text not found in ${path}.`);
  }
  const next = current.split(oldText).join(newText);
  const count = current.split(oldText).length - 1;
  await ctx.app.vault.modify(file, next);
  new import_obsidian4.Notice(`Updated ${path}`);
  return `Replaced ${count} occurrence${count === 1 ? "" : "s"} in ${path}.`;
}

// src/chat.ts
var ChatSession = class {
  constructor(app) {
    this.app = app;
    this.messages = [];
    this.history = [];
    this.busy = false;
    this.workingLabel = "";
    this.generation = 0;
    this.listeners = /* @__PURE__ */ new Set();
  }
  onChange(listener) {
    this.listeners.add(listener);
    return () => this.listeners.delete(listener);
  }
  emit() {
    for (const listener of this.listeners) {
      listener();
    }
  }
  clear() {
    this.generation += 1;
    this.messages = [];
    this.history = [];
    this.busy = false;
    this.workingLabel = "";
    this.emit();
  }
  stop() {
    this.generation += 1;
    this.busy = false;
    this.workingLabel = "";
    this.emit();
  }
  async send(text, attachments, settings) {
    const trimmed = text.trim();
    if (!trimmed || this.busy) {
      return;
    }
    if (!settings.apiKey.trim()) {
      this.messages.push({
        id: uid(),
        role: "error",
        text: "Add an API key in Settings \u2192 Obsidinect, then try again."
      });
      this.emit();
      return;
    }
    const userContent = formatUserContent(trimmed, attachments);
    const mentionText = [trimmed, ...attachments.map((note) => note.path)].join("\n");
    this.messages.push({
      id: uid(),
      role: "user",
      text: trimmed,
      attachments: attachments.map((note) => note.path)
    });
    this.history.push({ role: "user", content: userContent });
    this.busy = true;
    this.workingLabel = "Thinking\u2026";
    this.emit();
    const gen = this.generation;
    const provider = getProvider(settings.provider);
    try {
      for (let round = 0; round < MAX_TOOL_ROUNDS; round++) {
        if (gen !== this.generation) {
          return;
        }
        this.workingLabel = round === 0 ? "Thinking\u2026" : "Using vault tools\u2026";
        this.emit();
        const turn = await provider.complete({
          settings,
          systemPrompt: settings.systemPrompt,
          messages: this.history
        });
        if (gen !== this.generation) {
          return;
        }
        if (turn.toolCalls.length === 0) {
          const reply = turn.text.trim() || "(No text returned.)";
          this.history.push({ role: "assistant", content: reply });
          this.messages.push({ id: uid(), role: "assistant", text: reply });
          return;
        }
        this.history.push({
          role: "assistant",
          content: turn.text,
          toolCalls: turn.toolCalls
        });
        const toolUi = {
          id: uid(),
          role: "tool",
          text: "Working in the vault",
          tools: turn.toolCalls.map((call) => ({ name: call.name, status: "running" }))
        };
        this.messages.push(toolUi);
        this.emit();
        const results = [];
        for (let i = 0; i < turn.toolCalls.length; i++) {
          const call = turn.toolCalls[i];
          this.workingLabel = toolLabel(call.name);
          this.emit();
          const result = await runVaultTool(call, {
            app: this.app,
            apiKey: settings.apiKey,
            userTurnText: mentionText
          });
          results.push(result);
          const row = toolUi.tools?.[i];
          if (row) {
            row.status = result.isError ? "error" : "done";
          }
          this.emit();
        }
        this.history.push({ role: "tool", results });
      }
      this.messages.push({
        id: uid(),
        role: "error",
        text: `Stopped after ${MAX_TOOL_ROUNDS} tool rounds. Ask a more specific follow-up.`
      });
    } catch (error) {
      if (gen !== this.generation) {
        return;
      }
      const message = error instanceof Error ? error.message : String(error);
      this.messages.push({
        id: uid(),
        role: "error",
        text: redactSecrets(message, settings.apiKey)
      });
    } finally {
      if (gen === this.generation) {
        this.busy = false;
        this.workingLabel = "";
        this.emit();
      }
    }
  }
};
async function completePlainText(instruction, source, settings) {
  if (!settings.apiKey.trim()) {
    throw new Error("Add an API key in Settings \u2192 Obsidinect.");
  }
  const provider = getProvider(settings.provider);
  const systemPrompt = [
    "You edit markdown for an Obsidian note.",
    "Return only the edited markdown. No preface, no explanation, no surrounding code fences unless the source already used them.",
    "Never include API keys."
  ].join(" ");
  const turn = await provider.complete({
    settings,
    systemPrompt,
    disableTools: true,
    messages: [
      {
        role: "user",
        content: `Instruction:
${instruction}

Markdown to edit:
${source}`
      }
    ]
  });
  if (!turn.text.trim()) {
    throw new Error("The model returned an empty edit.");
  }
  return turn.text;
}
function formatUserContent(text, attachments) {
  if (attachments.length === 0) {
    return text;
  }
  const blocks = attachments.map((note) => {
    return `### ${note.path}
${truncate(note.content, MAX_ATTACH_CHARS)}`;
  });
  return `${text}

Attached notes:

${blocks.join("\n\n")}`;
}
function toolLabel(name) {
  switch (name) {
    case "list_notes":
      return "Listing notes\u2026";
    case "read_note":
      return "Reading a note\u2026";
    case "search_notes":
      return "Searching the vault\u2026";
    case "write_note":
      return "Writing a note\u2026";
    case "append_note":
      return "Appending a note\u2026";
    case "replace_in_note":
      return "Editing a note\u2026";
    default:
      return "Working\u2026";
  }
}
function redactSecrets(message, apiKey) {
  if (apiKey && apiKey.length >= 8) {
    return message.split(apiKey).join("[redacted]");
  }
  return message;
}
function uid() {
  return `${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 8)}`;
}

// src/inline-edit.ts
var import_obsidian5 = require("obsidian");
function getInlineEditTarget(app) {
  const view = app.workspace.getActiveViewOfType(import_obsidian5.MarkdownView);
  const file = view?.file;
  if (!file) {
    return null;
  }
  const editor = view.editor;
  const selected = editor.getSelection();
  if (selected) {
    return {
      file,
      selected,
      from: editor.posToOffset(editor.getCursor("from")),
      to: editor.posToOffset(editor.getCursor("to"))
    };
  }
  return { file, selected: "" };
}
var InlineEditModal = class extends import_obsidian5.Modal {
  constructor(app, settings, target, source) {
    super(app);
    this.settings = settings;
    this.target = target;
    this.source = source;
    this.instruction = "";
    this.after = "";
    this.busy = false;
  }
  onOpen() {
    this.titleEl.setText(this.target.selected ? "Inline edit selection" : "Inline edit note");
    this.modalEl.addClass("obsidinect-inline-modal");
    const scope = this.contentEl.createDiv({ cls: "obsidinect-inline-scope" });
    scope.setText(
      this.target.selected ? `Editing a selection in ${this.target.file.path}` : `Editing all of ${this.target.file.path}`
    );
    new import_obsidian5.Setting(this.contentEl).setName("Instruction").setDesc("What should change?").addTextArea((area) => {
      area.setPlaceholder("Tighten this, keep the meaning, keep wiki links.");
      area.inputEl.addClass("obsidinect-inline-instruction");
      area.inputEl.rows = 3;
      area.onChange((value) => {
        this.instruction = value;
      });
      area.inputEl.focus();
    });
    new import_obsidian5.Setting(this.contentEl).addButton(
      (btn) => btn.setButtonText("Preview edit").setCta().onClick(() => void this.preview())
    );
    this.previewEl = this.contentEl.createDiv({ cls: "obsidinect-inline-preview" });
    this.renderPreview();
    new import_obsidian5.Setting(this.contentEl).addButton((btn) => {
      this.applyBtn = btn.buttonEl;
      btn.setButtonText("Apply").setDisabled(true).onClick(() => void this.apply());
    });
  }
  renderPreview() {
    this.previewEl.empty();
    const before = this.previewEl.createDiv({ cls: "obsidinect-inline-col" });
    before.createEl("h4", { text: "Before" });
    before.createEl("pre", { text: this.source || "(empty note)" });
    const after = this.previewEl.createDiv({ cls: "obsidinect-inline-col" });
    after.createEl("h4", { text: "After" });
    if (this.busy) {
      after.createEl("p", { text: "Working\u2026", cls: "obsidinect-muted" });
    } else if (this.after) {
      after.createEl("pre", { text: this.after });
    } else {
      after.createEl("p", { text: "Preview will appear here.", cls: "obsidinect-muted" });
    }
  }
  async preview() {
    if (this.busy) {
      return;
    }
    const instruction = this.instruction.trim();
    if (!instruction) {
      new import_obsidian5.Notice("Write an instruction first.");
      return;
    }
    this.busy = true;
    this.after = "";
    this.applyBtn.disabled = true;
    this.renderPreview();
    try {
      const raw = await completePlainText(instruction, this.source, this.settings);
      this.after = stripWrappingFences(raw);
      this.applyBtn.disabled = false;
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      new import_obsidian5.Notice(message);
    } finally {
      this.busy = false;
      this.renderPreview();
    }
  }
  async apply() {
    if (!this.after) {
      return;
    }
    const view = this.app.workspace.getActiveViewOfType(import_obsidian5.MarkdownView);
    const editor = view?.file?.path === this.target.file.path ? view.editor : null;
    if (editor && this.target.selected && this.target.from != null && this.target.to != null) {
      const from = editor.offsetToPos(this.target.from);
      const to = editor.offsetToPos(this.target.to);
      editor.replaceRange(this.after, from, to);
    } else if (editor && !this.target.selected) {
      editor.setValue(this.after);
    } else {
      await this.app.vault.modify(this.target.file, this.after);
    }
    new import_obsidian5.Notice(`Applied edit to ${this.target.file.path}`);
    this.close();
  }
};
async function openInlineEdit(app, settings) {
  const target = getInlineEditTarget(app);
  if (!target) {
    new import_obsidian5.Notice("Open a markdown note first.");
    return;
  }
  const source = target.selected || await app.vault.cachedRead(target.file);
  if (!source.trim() && !target.selected) {
    new import_obsidian5.Notice("This note is empty.");
  }
  new InlineEditModal(app, settings, target, source).open();
}

// src/settings.ts
var import_obsidian6 = require("obsidian");
var ObsidinectSettingTab = class extends import_obsidian6.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Claudius" });
    containerEl.createEl("p", {
      text: "HTTPS chat for iPhone and desktop. Keys stay in this plugin\u2019s data file and are never written to notes.",
      cls: "obsidinect-settings-lead"
    });
    new import_obsidian6.Setting(containerEl).setName("Provider").setDesc("Claude is the default. OpenAI-compatible servers work via a custom base URL.").addDropdown((dropdown) => {
      Object.keys(PROVIDER_LABELS).forEach((id) => {
        dropdown.addOption(id, PROVIDER_LABELS[id]);
      });
      dropdown.setValue(this.plugin.settings.provider);
      dropdown.onChange(async (value) => {
        const provider = value;
        this.plugin.settings.provider = provider;
        const current = this.plugin.settings.model;
        const known = Object.values(DEFAULT_MODELS);
        if (!current || known.includes(current)) {
          this.plugin.settings.model = DEFAULT_MODELS[provider];
        }
        await this.plugin.saveSettings();
        this.display();
      });
    });
    new import_obsidian6.Setting(containerEl).setName("API key").setDesc("Stored in this plugin\u2019s data.json. Never logged, never written into notes.").addText((text) => {
      text.inputEl.type = "password";
      text.inputEl.autocomplete = "off";
      text.setPlaceholder(this.plugin.settings.provider === "anthropic" ? "sk-ant-\u2026" : "sk-\u2026");
      text.setValue(this.plugin.settings.apiKey);
      text.onChange(async (value) => {
        this.plugin.settings.apiKey = value.trim();
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian6.Setting(containerEl).setName("Model").setDesc(`Default for this provider: ${DEFAULT_MODELS[this.plugin.settings.provider]}`).addText((text) => {
      text.setPlaceholder(DEFAULT_MODELS[this.plugin.settings.provider]);
      text.setValue(this.plugin.settings.model);
      text.onChange(async (value) => {
        this.plugin.settings.model = value.trim() || DEFAULT_MODELS[this.plugin.settings.provider];
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian6.Setting(containerEl).setName("Custom base URL").setDesc(
      `Optional. Leave blank for ${DEFAULT_BASE_URLS[this.plugin.settings.provider]}. Use this for OpenAI-compatible proxies.`
    ).addText((text) => {
      text.setPlaceholder(DEFAULT_BASE_URLS[this.plugin.settings.provider]);
      text.setValue(this.plugin.settings.baseUrl);
      text.onChange(async (value) => {
        this.plugin.settings.baseUrl = value.trim();
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian6.Setting(containerEl).setName("System prompt").setDesc("Sent with every chat turn. Tools are still available.").addTextArea((area) => {
      area.inputEl.rows = 6;
      area.inputEl.addClass("obsidinect-system-prompt");
      area.setValue(this.plugin.settings.systemPrompt);
      area.onChange(async (value) => {
        this.plugin.settings.systemPrompt = value || DEFAULT_SYSTEM_PROMPT;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian6.Setting(containerEl).setName("Reset system prompt").addButton(
      (btn) => btn.setButtonText("Restore default").onClick(async () => {
        this.plugin.settings.systemPrompt = DEFAULT_SYSTEM_PROMPT;
        await this.plugin.saveSettings();
        this.display();
      })
    );
    new import_obsidian6.Setting(containerEl).setName("Test connection").setDesc("Sends a tiny HTTPS request with requestUrl. The key is not printed.").addButton(
      (btn) => btn.setButtonText("Test connection").setCta().onClick(async () => {
        btn.setDisabled(true);
        btn.setButtonText("Testing\u2026");
        try {
          await testConnection(this.plugin.settings);
          new import_obsidian6.Notice("Obsidinect: connection succeeded.");
        } catch (error) {
          const message = error instanceof Error ? error.message : String(error);
          const key = this.plugin.settings.apiKey;
          const safe = key && key.length >= 8 ? message.split(key).join("[redacted]") : message;
          new import_obsidian6.Notice(`Obsidinect: ${safe}`);
        } finally {
          btn.setDisabled(false);
          btn.setButtonText("Test connection");
        }
      })
    );
    containerEl.createEl("h3", { text: "Privacy" });
    containerEl.createEl("p", {
      cls: "obsidinect-settings-lead",
      text: "A chat sends your prompt, attached notes, and later tool results only to the provider you picked (Anthropic, OpenAI, xAI, or your custom base URL). Nothing else is contacted. API keys stay in this device\u2019s plugin data and are never written into notes. There is no telemetry."
    });
  }
};
async function testConnection(settings) {
  if (!settings.apiKey.trim()) {
    throw new Error("Add an API key first.");
  }
  const provider = getProvider(settings.provider);
  const turn = await provider.complete({
    settings,
    systemPrompt: "Reply with the single word pong.",
    disableTools: true,
    messages: [{ role: "user", content: "ping" }]
  });
  if (!turn.text && turn.toolCalls.length === 0) {
    throw new Error("The provider returned an empty response.");
  }
}

// src/view.ts
var import_obsidian8 = require("obsidian");

// src/suggester.ts
var import_obsidian7 = require("obsidian");
var NoteAttachModal = class extends import_obsidian7.FuzzySuggestModal {
  constructor(app, onPick) {
    super(app);
    this.onPick = onPick;
    this.setPlaceholder("Attach a note to this message");
  }
  getItems() {
    return this.app.vault.getMarkdownFiles();
  }
  getItemText(file) {
    return file.path;
  }
  onChooseItem(file) {
    this.onPick(file);
  }
};
function mentionQuery(value, cursor) {
  const before = value.slice(0, cursor);
  const at = before.lastIndexOf("@");
  if (at < 0) {
    return null;
  }
  if (at > 0) {
    const prev = before[at - 1];
    if (prev && !/\s/.test(prev)) {
      return null;
    }
  }
  const query = before.slice(at + 1);
  if (query.includes("\n") || query.includes(" ")) {
    return null;
  }
  return { start: at, query };
}
function suggestNotes(app, query, limit = 12) {
  const files = app.vault.getMarkdownFiles();
  const needle = query.toLowerCase();
  const scored = files.map((file) => ({ file, score: scoreFile(file, needle) })).filter((row) => row.score > 0 || needle.length === 0).sort((a, b) => b.score - a.score || a.file.path.localeCompare(b.file.path));
  return scored.slice(0, limit).map((row) => row.file);
}
function scoreFile(file, needle) {
  if (!needle) {
    return 1;
  }
  const path = file.path.toLowerCase();
  const name = file.basename.toLowerCase();
  if (name === needle) {
    return 100;
  }
  if (name.startsWith(needle)) {
    return 80;
  }
  if (name.includes(needle)) {
    return 60;
  }
  if (path.includes(needle)) {
    return 40;
  }
  return 0;
}

// src/view.ts
var ObsidinectView = class extends import_obsidian8.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.plugin = plugin;
    this.attachments = [];
    this.mentionHits = [];
    this.mentionStart = -1;
    this.mentionIndex = 0;
    this.unsubscribe = null;
  }
  getViewType() {
    return VIEW_TYPE_OBSIDINECT;
  }
  getDisplayText() {
    return "Claudius";
  }
  getIcon() {
    return "bot";
  }
  async onOpen() {
    this.contentEl.empty();
    this.contentEl.addClass("obsidinect-leaf");
    this.root = this.contentEl.createDiv({ cls: "obsidinect-root" });
    this.buildHeader();
    this.listEl = this.root.createDiv({ cls: "obsidinect-messages" });
    this.statusEl = this.root.createDiv({ cls: "obsidinect-status" });
    this.chipsEl = this.root.createDiv({ cls: "obsidinect-chips" });
    this.suggestEl = this.root.createDiv({ cls: "obsidinect-suggest" });
    this.suggestEl.hide();
    this.buildComposer();
    this.unsubscribe = this.plugin.session.onChange(() => this.render());
    this.render();
    this.bindViewport();
  }
  async onClose() {
    this.unsubscribe?.();
    this.unsubscribe = null;
  }
  buildHeader() {
    const header = this.root.createDiv({ cls: "obsidinect-header" });
    const title = header.createDiv({ cls: "obsidinect-title" });
    const icon = title.createSpan({ cls: "obsidinect-title-icon" });
    (0, import_obsidian8.setIcon)(icon, "bot");
    title.createSpan({ text: "Claudius" });
    const actions = header.createDiv({ cls: "obsidinect-header-actions" });
    this.iconButton(actions, "eraser", "New chat", () => {
      this.plugin.session.clear();
      this.attachments = [];
      this.renderChips();
    });
    this.iconButton(actions, "settings", "Open settings", () => {
      const setting = this.app.setting;
      if (setting) {
        setting.open();
        setting.openTabById(this.plugin.manifest.id);
      }
    });
  }
  buildComposer() {
    const composer = this.root.createDiv({ cls: "obsidinect-composer" });
    const row = composer.createDiv({ cls: "obsidinect-composer-row" });
    this.iconButton(row, "at-sign", "Attach a note", () => {
      new NoteAttachModal(this.app, (file) => void this.attachFile(file)).open();
    });
    this.textarea = row.createEl("textarea", {
      cls: "obsidinect-input",
      attr: {
        rows: "1",
        placeholder: "Ask about your vault. Type @ to attach a note.",
        enterkeyhint: "send"
      }
    });
    this.textarea.addEventListener("input", () => {
      this.autosize();
      this.updateMention();
    });
    this.textarea.addEventListener("keydown", (event) => this.onKey(event));
    this.sendBtn = row.createEl("button", { cls: "obsidinect-send", attr: { type: "button" } });
    (0, import_obsidian8.setIcon)(this.sendBtn, "send");
    this.sendBtn.setAttr("aria-label", "Send");
    this.sendBtn.addEventListener("click", () => {
      if (this.plugin.session.busy) {
        this.plugin.session.stop();
        return;
      }
      void this.submit();
    });
  }
  iconButton(parent, icon, label, onClick) {
    const button = parent.createEl("button", { cls: "obsidinect-icon-btn", attr: { type: "button" } });
    (0, import_obsidian8.setIcon)(button, icon);
    button.setAttr("aria-label", label);
    button.addEventListener("click", onClick);
    return button;
  }
  bindViewport() {
    const viewport = window.visualViewport;
    if (!viewport) {
      return;
    }
    const sync = () => {
      const inset = Math.max(0, window.innerHeight - viewport.height - viewport.offsetTop);
      this.root.style.setProperty("--obsidinect-keyboard", `${inset}px`);
    };
    viewport.addEventListener("resize", sync);
    viewport.addEventListener("scroll", sync);
    this.register(() => {
      viewport.removeEventListener("resize", sync);
      viewport.removeEventListener("scroll", sync);
    });
    sync();
  }
  render() {
    this.renderMessages();
    this.renderStatus();
    this.renderChips();
    const { busy } = this.plugin.session;
    this.sendBtn.disabled = false;
    (0, import_obsidian8.setIcon)(this.sendBtn, busy ? "square" : "send");
    this.sendBtn.setAttr("aria-label", busy ? "Stop" : "Send");
    this.sendBtn.toggleClass("is-stop", busy);
  }
  renderMessages() {
    const { messages } = this.plugin.session;
    this.listEl.empty();
    if (messages.length === 0) {
      const empty = this.listEl.createDiv({ cls: "obsidinect-empty" });
      empty.createEl("h3", { text: "Chat with your vault" });
      empty.createEl("p", {
        text: this.plugin.settings.apiKey ? "Ask to find, summarize, or edit notes. Type @ or tap the @ button to attach a file." : "Add an API key in Settings \u2192 Obsidinect, then come back here."
      });
      return;
    }
    for (const message of messages) {
      this.renderMessage(message);
    }
    this.listEl.scrollTop = this.listEl.scrollHeight;
  }
  renderMessage(message) {
    const bubble = this.listEl.createDiv({ cls: `obsidinect-bubble is-${message.role}` });
    if (message.role === "assistant" || message.role === "user") {
      const body = bubble.createDiv({ cls: "obsidinect-md" });
      void import_obsidian8.MarkdownRenderer.render(this.app, message.text, body, "", this);
    } else {
      bubble.createDiv({ cls: "obsidinect-plain", text: message.text });
    }
    if (message.attachments?.length) {
      const meta = bubble.createDiv({ cls: "obsidinect-meta" });
      meta.setText(message.attachments.map((path) => `@${path}`).join(" \xB7 "));
    }
    if (message.tools?.length) {
      const tools = bubble.createDiv({ cls: "obsidinect-tools" });
      for (const tool of message.tools) {
        const row = tools.createDiv({ cls: `obsidinect-tool is-${tool.status}` });
        row.setText(`${toolLabel2(tool.name)} \xB7 ${tool.status}`);
      }
    }
  }
  renderStatus() {
    const { busy, workingLabel } = this.plugin.session;
    this.statusEl.toggleClass("is-busy", busy);
    this.statusEl.setText(busy ? workingLabel || "Working\u2026" : "");
    if (busy) {
      this.statusEl.show();
    } else {
      this.statusEl.hide();
    }
  }
  renderChips() {
    this.chipsEl.empty();
    for (const note of this.attachments) {
      const chip = this.chipsEl.createDiv({ cls: "obsidinect-chip" });
      chip.createSpan({ text: note.path });
      const remove = chip.createEl("button", { cls: "obsidinect-chip-x", attr: { type: "button" } });
      (0, import_obsidian8.setIcon)(remove, "x");
      remove.setAttr("aria-label", `Remove ${note.path}`);
      remove.addEventListener("click", () => {
        this.attachments = this.attachments.filter((item) => item.path !== note.path);
        this.renderChips();
      });
    }
  }
  autosize() {
    this.textarea.style.height = "auto";
    this.textarea.style.height = `${Math.min(this.textarea.scrollHeight, 160)}px`;
  }
  onKey(event) {
    if (this.suggestEl.isShown() && this.mentionHits.length > 0) {
      if (event.key === "ArrowDown") {
        event.preventDefault();
        this.mentionIndex = (this.mentionIndex + 1) % this.mentionHits.length;
        this.paintSuggestions();
        return;
      }
      if (event.key === "ArrowUp") {
        event.preventDefault();
        this.mentionIndex = (this.mentionIndex - 1 + this.mentionHits.length) % this.mentionHits.length;
        this.paintSuggestions();
        return;
      }
      if (event.key === "Enter" || event.key === "Tab") {
        event.preventDefault();
        const file = this.mentionHits[this.mentionIndex];
        if (file) {
          void this.chooseMention(file);
        }
        return;
      }
      if (event.key === "Escape") {
        this.closeMention();
        return;
      }
    }
    if (event.key === "Enter" && !event.shiftKey && !import_obsidian8.Platform.isMobile) {
      event.preventDefault();
      void this.submit();
    }
  }
  updateMention() {
    const cursor = this.textarea.selectionStart ?? this.textarea.value.length;
    const mention = mentionQuery(this.textarea.value, cursor);
    if (!mention) {
      this.closeMention();
      return;
    }
    this.mentionStart = mention.start;
    this.mentionHits = suggestNotes(this.app, mention.query);
    this.mentionIndex = 0;
    this.paintSuggestions();
  }
  paintSuggestions() {
    this.suggestEl.empty();
    if (this.mentionHits.length === 0) {
      this.suggestEl.createDiv({ cls: "obsidinect-suggest-empty", text: "No matching notes" });
      this.suggestEl.show();
      return;
    }
    this.mentionHits.forEach((file, index) => {
      const row = this.suggestEl.createDiv({
        cls: `obsidinect-suggest-item${index === this.mentionIndex ? " is-active" : ""}`
      });
      row.createDiv({ cls: "obsidinect-suggest-name", text: file.basename });
      row.createDiv({ cls: "obsidinect-suggest-path", text: file.path });
      row.addEventListener("click", () => void this.chooseMention(file));
    });
    this.suggestEl.show();
  }
  closeMention() {
    this.mentionHits = [];
    this.mentionStart = -1;
    this.suggestEl.hide();
    this.suggestEl.empty();
  }
  async chooseMention(file) {
    if (this.mentionStart >= 0) {
      const cursor = this.textarea.selectionStart ?? this.textarea.value.length;
      const before = this.textarea.value.slice(0, this.mentionStart);
      const after = this.textarea.value.slice(cursor);
      this.textarea.value = `${before}${after}`;
      this.textarea.setSelectionRange(before.length, before.length);
    }
    this.closeMention();
    await this.attachFile(file);
    this.autosize();
    this.textarea.focus();
  }
  async attachFile(file) {
    if (this.attachments.some((note) => note.path === file.path)) {
      return;
    }
    const content = await this.app.vault.cachedRead(file);
    this.attachments.push({ path: file.path, content });
    this.renderChips();
  }
  async submit() {
    const text = this.textarea.value.trim();
    if (!text || this.plugin.session.busy) {
      return;
    }
    const attached = [...this.attachments];
    this.textarea.value = "";
    this.autosize();
    this.attachments = [];
    this.closeMention();
    this.renderChips();
    await this.plugin.session.send(text, attached, this.plugin.settings);
  }
};
function toolLabel2(name) {
  return name.replace(/_/g, " ");
}

// src/main.ts
var ObsidinectPlugin = class extends import_obsidian9.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
    this.decorated = /* @__PURE__ */ new WeakSet();
  }
  async onload() {
    await this.loadSettings();
    this.session = new ChatSession(this.app);
    this.registerView(VIEW_TYPE_OBSIDINECT, (leaf) => new ObsidinectView(leaf, this));
    this.addRibbonIcon("bot", "Open Claudius chat", () => {
      void this.activateView();
    });
    this.addCommand({
      id: "open-obsidinect-chat",
      name: "Open Claudius chat",
      callback: () => {
        void this.activateView();
      }
    });
    this.addCommand({
      id: "new-chat",
      name: "New chat",
      callback: () => {
        this.session.clear();
        void this.activateView();
      }
    });
    this.addCommand({
      id: "obsidinect-inline-edit",
      name: "Inline edit",
      editorCallback: () => {
        void openInlineEdit(this.app, this.settings);
      }
    });
    this.addCommand({
      id: "obsidinect-inline-edit-current-note",
      name: "Inline edit current note",
      callback: () => {
        void openInlineEdit(this.app, this.settings);
      }
    });
    this.registerEvent(
      this.app.workspace.on("editor-menu", (menu) => {
        menu.addItem((item) => {
          item.setTitle("Inline edit with Obsidinect").setIcon("pencil").onClick(() => {
            void openInlineEdit(this.app, this.settings);
          });
        });
      })
    );
    this.addSettingTab(new ObsidinectSettingTab(this.app, this));
    this.registerEvent(this.app.workspace.on("layout-change", () => this.decorateEditors()));
    this.app.workspace.onLayoutReady(() => this.decorateEditors());
  }
  onunload() {
    this.session?.stop();
  }
  async activateView() {
    const { workspace } = this.app;
    const existing = workspace.getLeavesOfType(VIEW_TYPE_OBSIDINECT);
    const leaf = existing[0] ?? workspace.getRightLeaf(false) ?? workspace.getLeaf(true);
    if (!existing[0]) {
      await leaf.setViewState({ type: VIEW_TYPE_OBSIDINECT, active: true });
    }
    workspace.revealLeaf(leaf);
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  decorateEditors() {
    for (const leaf of this.app.workspace.getLeavesOfType("markdown")) {
      const view = leaf.view;
      if (!(view instanceof import_obsidian9.MarkdownView) || this.decorated.has(view)) {
        continue;
      }
      this.decorated.add(view);
      view.addAction("pencil", "Inline edit with Obsidinect", () => {
        void openInlineEdit(this.app, this.settings);
      });
    }
  }
};
